Repository LemurPwned/VISM, pull requests merged in 2018-06, with the labels that each got.

#120 Issues/106
  .gitignore
  ColorPolicy.py
  Widgets/openGL_widgets/AbstractGLContext.py
  Widgets/openGL_widgets/ArrowGLContext.py
  Widgets/openGL_widgets/VectorGLContext.py
  Windows/PerfOptions.py
  Windows/widget_pane.json
  buildVerifier.py
  debugging/autoLoadMain.py
  main.py
  multiprocessing_parse.py
Labels: Before Release

#118 Iss103
  PopUp.py
  Widgets/openGL_widgets/AbstractGLContext.py
  Widgets/openGL_widgets/ArrowGLContext.py
  Widgets/openGL_widgets/CubicGLContext.py
  Widgets/openGL_widgets/VectorGLContext.py
  Widgets/plot_widgets/AbstractCanvas.py
  Widgets/plot_widgets/Canvas.py
  Widgets/plot_widgets/CanvasLayer.py
  Windows/PerfOptions.py
  Windows/PlayerWindow.py
  Windows/PlotSettings.py
  Windows/SimplePerfOptions.py
  main.py
  pattern_types/Patterns.py
  settingsMediator/settingsLoader.py
  settingsMediator/settingsPrompter.py
  video_utils/video_composer.py
  widget_counter.py
Labels: Before Release, bug, urgent

#116 Issues/108
  .gitignore
  AnimatedWidget.py
  ColorPolicy.py
  WidgetHandler.py
  Widgets/openGL_widgets/AbstractGLContext.py
  Widgets/openGL_widgets/CubicGLContext.py
  Widgets/plot_widgets/AbstractCanvas.py
  Widgets/plot_widgets/Canvas.py
  Widgets/plot_widgets/Canvas2Dupgraded.py
  Windows/ChooseWidget.py
  Windows/MainWindowTemplate.py
  Windows/PerfOptions.py
  Windows/PerfOptionsTemplate.py
  Windows/PlayerWindow.py
  Windows/PlotSettings.py
  Windows/PlotSettingsTemplate.py
  Windows/SelectTemplate.py
  Windows/SimplePerfOptionsTemplate.py
  Windows/UI_files/PerfOptions.ui
  Windows/animationSettingsTemplate.py
  Windows/widget_pane.json
  cython_modules/color_policy.c
  cython_modules/color_policy.pyx
  cython_modules/cython_parse.c
  cython_modules/cython_parse.pyx
  installation.bat
  main.py
  multiprocessing_parse.py
  pattern_types/Patterns.py
  settingsMediator/settingsLoader.py
  settingsMediator/settingsPrompter.py
Labels: Before Release, urgent
